# Generated by Django 4.2 on 2023-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_useremail_userpswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
