# Generated by Django 4.2 on 2023-09-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_alter_useremail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpswd',
            name='pswd',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
